baseURL: https://cmna-workshop.github.io/cmna25
languageCode: en-gb
title: CMNA'25
theme: PaperModX
publishDir: docs
params:
  description: "Theme PaperModX - https://github.com/reorx/hugo-PaperModX"
  author:
    - Simon
  homeInfoParams:
    Title: "The 25th International Workshop on Computational Models of Natural Argument (CMNA'25)"
    Content: |
        The forthcoming 25th Edition of the Workshop on Computational Models of Natural Argument (CMNA'25) will be held independently & online as we celebrate twenty-five years of this workshop series and look forward to a furth twenty-five more.

        We are pleased to invite submissions for our forthcoming 25th annual edition of the workshop on Computational Models of Natural Argument (CMNA'25). The CMNA workshop series focuses on the issue of modelling "natural" argumentation, where naturalness may range across a variety of forms, perhaps involving the use of visual rather than linguistic means to illustrate a point, for example using graphics or multimedia, or applying more sophisticated rhetorical devices, interacting at various layers of abstraction, or exploiting “extra-rational” characteristics of the audience, taking into account emotions and affective factors. For this edition, CMNA will be run online as virtual workshop.

        To celebrate this landmark year, we solicit contributions on the special theme of **"Reflections & Horizons: The past 25 years of Computational Models of Natural Argument and visions of things to come"**. This theme should be interpreted broadly, to reflect the wide range of argumentative practices and models that have been studied and shared at CMNA. We also encourage reflection on the development of argumentation theory within the remit of CMNA during the last 25 years. Finally we also encourage forward looking contributions that share a vision of how argumentation research might develop over the next quarter century.

        Finally, we also solicit papers concerned with the full range of <a href="topics/" style="text-decoration:underline">topics</a> that CMNA usually focusses upon.

  defaultTheme: auto
  ShowPostNavLinks: true
  #ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  TocOpen: true
  TocSide: "right"
  EnableInstantClick: true
  EnableImageZoom: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: News
          url: /news/
          weight: 1
        - name: Topics
          url: /topics/
          weight: 1
        - name: Submission
          url: /submission/
          weight: 4
        - name: Dates
          url: /dates/
          weight: 5
        - name: Organisation
          url: /organisation/
          weight: 10
        - name: Programme
          url: /programme/
          weight: 12
        - name: Sponsors
          url: /sponsors/
          weight: 14
        - name: About
          url: /about/
          weight: 15

outputs:
  home:
    - HTML
    - RSS
    - JSON

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false
